"""Python<->R parity gate for the rtSD MEDv4 model.

Proves the public-facing Python implementation (python/rtsd/model.py, used by
the marimo notebook) reproduces the validated R reference (R/simulate.R via
deSolve euler, the Vensim/PySD-anchored authority) within tolerance.

R is the golden source: golden trajectories are generated by
tests/parity/generate_golden.R (run in Docker, where deSolve lives) and
committed under tests/parity/golden/. This test runs in pure Python and
compares against them. If a golden is missing the case is SKIPPED with a
pointer to the generator, so the suite is green-or-skip until goldens land.

Both sides read tests/parity/cases.json, so inputs are identical by
construction (eliminates param-name divergence D1 and grid divergence D2 as
silent failure modes).
"""

import json
import sys
from pathlib import Path

import numpy as np
import pytest

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(REPO / "python" / "rtsd"))

import model  # noqa: E402  (path-dependent import)

SPEC = json.loads((HERE / "cases.json").read_text())
GOLDEN_DIR = HERE / "golden"
CASES = SPEC["cases"]
TOL = SPEC["tolerance"]


def _build_training_fn(case, grid):
    f = case["forcing"]
    if f["type"] == "constant":
        val = float(f["value"])
        return lambda t: val
    if f["type"] == "events":
        sched = model.pulse_from_events(
            grid,
            np.asarray(f["times"], dtype=float),
            np.asarray(f["heights"], dtype=float),
            width=float(f.get("width", 1.0 / 7.0)),
        )
        return model.make_training_fn(grid, sched)
    raise ValueError(f"unknown forcing type: {f['type']}")


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_python_matches_r_reference(case):
    golden_path = GOLDEN_DIR / f"{case['name']}.csv"
    if not golden_path.exists():
        pytest.skip(
            f"golden missing ({golden_path.name}); generate with "
            "`docker compose run --rm parity-golden` (tests/parity/generate_golden.R)"
        )

    params = dict(SPEC["params"])
    horizon, dt = case["horizon"], case["dt"]
    grid = np.arange(0.0, horizon + dt, dt)
    training_fn = _build_training_fn(case, grid)

    g_py, out_py = model.simulate(params, horizon, dt, training_fn, case["variant"])

    gold = np.genfromtxt(golden_path, delimiter=",", names=True)
    t_r = np.atleast_1d(gold["time"])
    out_r = np.column_stack([gold["Fitness"], gold["Fatigue"], gold["Signal"]])

    # D2: grids must align before any element-wise comparison is meaningful.
    assert len(g_py) == len(t_r), (
        f"{case['name']}: grid length mismatch py={len(g_py)} r={len(t_r)} "
        "(np.arange vs seq endpoint divergence)"
    )
    np.testing.assert_allclose(
        g_py, t_r, rtol=0, atol=1e-9,
        err_msg=f"{case['name']}: time grids differ",
    )

    assert np.all(np.isfinite(out_py)), f"{case['name']}: Python trajectory non-finite"
    assert np.all(np.isfinite(out_r)), f"{case['name']}: R golden trajectory non-finite"

    np.testing.assert_allclose(
        out_py, out_r,
        rtol=TOL["rtol"], atol=TOL["atol"],
        err_msg=f"{case['name']}: Python model diverges from R reference",
    )
