#!/usr/bin/env python3
"""Build a self-contained, WASM-exportable copy of the rtSD Explorer notebook.

`marimo export html-wasm` bundles ONLY the notebook file — it does NOT include
sibling local modules (`model.py`, `sd_diagram.py`); see marimo issue #5488
(open as of v0.23.8). A raw export therefore throws `ModuleNotFoundError` in the
browser.

marimo does NOT execute top-level (non-cell) code before cells (verified), so
the inlining must be a *cell* whose output the import cells depend on. This
script produces `build/rtsd_wasm.py`:

  1. inserts a `_bootstrap` cell that decodes the inlined modules (base64) and
     registers them in `sys.modules`, returning a `_boot` sentinel;
  2. injects `_boot` into the signatures of the cells that import the local
     modules (`_model`, `_scenarios`, `_diagram`), forcing them to run after
     the bootstrap.

The notebook's `from model import ...` / `from sd_diagram import ...` then
resolve under Pyodide with no other edits.

Usage:
    python build_wasm.py            # write build/rtsd_wasm.py
    python build_wasm.py --export   # also run `marimo export html-wasm`

Edit rtsd.py / model.py / sd_diagram.py — NEVER the generated build file.
"""

import base64
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUILD = HERE / "build"
APP_MARKER = "app = marimo.App"

# Cells that import a local module -> inject the _boot sentinel into their
# signature so marimo schedules them after _bootstrap.
SIGNATURE_PATCHES = {
    "def _model():": "def _model(_boot):",
    "def _scenarios():": "def _scenarios(_boot):",
    "def _diagram(plt):": "def _diagram(_boot, plt):",
}


def _b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def _bootstrap_cell() -> str:
    inlined = {"model": _b64(HERE / "model.py"), "sd_diagram": _b64(HERE / "sd_diagram.py")}
    return (
        "@app.cell\n"
        "def _bootstrap():\n"
        '    """Generated by build_wasm.py: register inlined local modules in\n'
        "    sys.modules so `from model import ...` / `from sd_diagram import ...`\n"
        "    resolve under WASM/Pyodide, where export does not bundle sibling files.\n"
        "    Returns `_boot`, which the import cells depend on (ordering).\"\"\"\n"
        "    import sys as _sys, types as _types, base64 as _b64\n\n"
        f"    _INLINED = {inlined!r}\n\n"
        "    def _register_inlined(_name, _src_b64):\n"
        "        _src = _b64.b64decode(_src_b64).decode('utf-8')\n"
        "        _m = _types.ModuleType(_name)\n"
        "        _m.__file__ = _name + '.py'\n"
        "        exec(compile(_src, _name + '.py', 'exec'), _m.__dict__)\n"
        "        _sys.modules[_name] = _m\n\n"
        "    for _n, _s in _INLINED.items():\n"
        "        _register_inlined(_n, _s)\n"
        "    _boot = True\n"
        "    return (_boot,)\n"
    )


def build() -> Path:
    nb = (HERE / "rtsd.py").read_text(encoding="utf-8")

    # 1. Insert the bootstrap cell right after the App() line.
    out, inserted = [], False
    for line in nb.splitlines(keepends=True):
        out.append(line)
        if not inserted and line.startswith(APP_MARKER):
            out.append("\n\n" + _bootstrap_cell())
            inserted = True
    if not inserted:
        raise SystemExit(f"could not find '{APP_MARKER}' line to insert the bootstrap")
    text = "".join(out)

    # 2. Inject _boot into the import cells' signatures.
    for old, new in SIGNATURE_PATCHES.items():
        if old not in text:
            raise SystemExit(f"signature to patch not found: {old!r}")
        text = text.replace(old, new, 1)

    BUILD.mkdir(exist_ok=True)
    target = BUILD / "rtsd_wasm.py"
    target.write_text(text, encoding="utf-8")
    print(f"wrote {target}  ({target.stat().st_size // 1024} KB)")
    return target


def export(target: Path) -> None:
    out_dir = BUILD / "wasm"
    # Clean first so the bundle contains ONLY this export's output — no stale
    # files (e.g. a leftover CLAUDE.md) leaking into the deploy tarball.
    shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable, "-m", "marimo", "export", "html-wasm",
        str(target), "-o", str(out_dir / "index.html"), "--mode", "run",
    ]
    print("running:", " ".join(cmd))
    subprocess.run(cmd, check=True)
    # marimo's html-wasm export copies its bundled app assets (favicons,
    # manifest, logo) into the output AND sweeps in a stray CLAUDE.md from its
    # template; drop it so the deploy bundle/tarball is clean.
    stray = out_dir / "CLAUDE.md"
    if stray.exists():
        stray.unlink()
    print(f"WASM bundle written to {out_dir}/")


if __name__ == "__main__":
    t = build()
    if "--export" in sys.argv:
        export(t)
